stages:
  load_data:
    cmd: python src/stages/load_data.py --config=params.yaml
    params:
      - data_load
    deps:
      - src/stages/load_data.py
      - ${data_load.in}
    outs:
      - ${data_load.out}

  preprocess_data:
    cmd: python src/stages/preprocess_data.py --config=params.yaml
    params:
    - data_preproc
    deps:
      - src/stages/preprocess_data.py
      - ${data_preproc.in}
    outs:
      - ${data_preproc.out_X_train}
      - ${data_preproc.out_X_test}
      - ${data_preproc.out_y_train}
      - ${data_preproc.out_y_test}

  train_lr:
    cmd: python src/stages/train_lr.py --config=params.yaml
    params:
    - train_lr
    deps:
      - src/stages/train_lr.py
      - ${train_lr.in_X_train}
      - ${train_lr.in_y_train}
    outs:
      - ${train_lr.out}

  evaluate_model:
    cmd: python src/stages/evaluate_model.py --config=params.yaml
    deps:
      - ${train_lr.out}
      - src/stages/evaluate_model.py
      - ${evaluate_model.in_X_train}
      - ${evaluate_model.in_y_train}
      - ${evaluate_model.in_X_test}
      - ${evaluate_model.in_y_test}
