base:
  random_state: 42
  log_level: INFO

dvc_version: "v1.0.0"

config_path: "params.yaml"

data_load:
  in: 'data/raw/Algerian_forest_fires_dataset_UPDATE_RegionAdd.csv'
  out: 'data/interim/input_forest_fires.csv'
  repo: "https://github.com/A01794892-tec-mx/MLOpsEq21.git"
  
data_preproc:
  in: 'data/interim/input_forest_fires.csv'
  out_X_train: 'data/processed/X_train.csv'
  out_X_test: 'data/processed/X_test.csv'
  out_y_train: 'data/processed/y_train.csv'
  out_y_test: 'data/processed/y_test.csv'

train_lr:
  in_X_train: 'data/processed/X_train.csv'
  in_y_train: 'data/processed/y_train.csv'

  model_LR:
    modelName: 'modelLR'
    penalty: 'l1'
    C: 10
    solver: 'liblinear'
    max_iter: 1000
    random_state: 52
  
  out: 'models'

evaluate_model:
  in: 'models'
  in_X_train: 'data/processed/X_train.csv'
  in_X_test: 'data/processed/X_test.csv'
  in_y_train: 'data/processed/y_train.csv'
  in_y_test: 'data/processed/y_test.csv'
  out: 'reports'

mlflow:
  host: "http://localhost:5000"
  experiment_name: "Algerian_Forest_Fires_Experiment"